### PR TITLE
update the App name

### PR DESCRIPTION
**Pull request by freiburgermsu**

### CODE REVIEW

**Review by pranjan77 — CHANGES_REQUESTED** [review]
use colon instead of semicolon in app name

**Comment by freiburgermsu** [comment]
@pranjan77 colon is syntactically used in YAML to introduce lists, so the file throws an error with a colon but not with a semi-colon after `CommScores`.

**Comment by pranjan77** [comment]
How about a - instead of ;

**Comment by pranjan77** [comment]
name: "Commscores : Calculate Metabolic Interaction Scores"
Quotes work too. I think we should use this.

**Comment by pranjan77** [comment]
Also ensure the urls for images work https://github.com/freiburgermsu/microbial_interactions/blob/main/ui/narrative/methods/run_microbial_interactions/BSS.png?sanitize=true      I don't see this.. Double check others.

**Comment by freiburgermsu** [comment]
The BSS image was accidentally omitted. All of the images are now in the repository.

**Pull request merged**
